name: Deploy Next.js Docker App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 using Docker
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}         # EC2 Public IP
          username: ${{ secrets.EC2_USER }}     # ec2-user
          key: ${{ secrets.EC2_KEY }}           # PEM private key content
          script: |
            cd happy            # Replace with exact folder name on EC2, e.g. 'happy'
            git pull origin master
            sudo docker stop nextjs || true
            sudo docker rm nextjs || true
            sudo docker build -t nextjs-app .
            sudo docker run -d -p 3000:3000 --name nextjs nextjs-app
