name: Deploy Next.js Docker App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e

            cd /home/ec2-user/happy
            git pull origin master

            docker stop happy-container || true
            docker rm happy-container || true

            docker build -t happy-image .
            docker run -d \
              -p 3000:3000 \
              --name happy-container \
              happy-image

              sudo docker system prune -f

